services:
  db:
    image: postgres:18.4
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/
    env_file:
      - ./.env

  app:
    build: .
    restart: always
    ports:
      - 8501:8501
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - web

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.theater.rule=Host(`theater.simonklug.de`)"
      - "traefik.http.routers.theater.entrypoints=websecure"
      - "traefik.http.routers.theater.tls.certresolver=letsencrypt"
      - "traefik.http.services.theater.loadbalancer.server.port=8501"

networks:
  web:
    external: true
